### ISSUE TITLE
Add directions button

### ISSUE THREAD

**Issue by spencer-shadley** [spencer-shadley/austinparks#17]
Directions from current location to the pool

**Comment by aliseisaksen** [comment]
Should our app handle this? Or should we just redirect the user to google maps for direction info?

**Comment by spencer-shadley** [comment]
I think either could work. Being that we are already using Google Maps' APIs it might be easy to inject directions directly. If it is too difficult, we can just direct the person somewhere else. 

Here is the Google Maps Directions API page https://developers.google.com/maps/documentation/directions/intro#RequestParameters

**Comment by spencer-shadley** [comment]
Here is a link to help inline it
https://developers.google.com/maps/documentation/javascript/reference#DirectionsRenderer

**Comment by spencer-shadley** [comment]
and here is an example 
http://jsfiddle.net/gHK7s/2/

**Comment by aliseisaksen** [comment]
I suppose my only worry here is that there are other pieces of our app that might be more critical. It's certainly a nice UX feature for the user, but it's also easily handled by sending the user off to maps.google.com with the coordinates for the selected pool.

**Comment by spencer-shadley** [comment]
I added the stretch goal label
