### ISSUE TITLE
Give closed pools a different icon color

### ISSUE THREAD

**Issue by aliseisaksen** [spencer-shadley/austinparks#19]
Blue?

**Comment by brdleyb** [comment]
Does it make sense to make open ones green and closed ones red?
I'll work on this code now since I have a little free time to work today

**Comment by spencer-shadley** [comment]
go for it, sounds good

**Comment by spencer-shadley** [comment]
we're creating green icons for you to use

**Comment by aliseisaksen** [comment]
Green icons have been created. They're in the assets folder.
