### ISSUE TITLE
Blue Column Width

### ISSUE THREAD

**Issue by ledennis** [spencer-shadley/austinparks#20]
The column isn't wide enough so that when the mouse is hovered over a pool name, the end of the text is hidden by the map.

**Comment by MorganEdgerton** [comment]
I will have the text wrap then.

**Comment by aliseisaksen** [comment]
@MorganEdgerton Did you ever get this finished? Im still seeing text become hidden on hover expand.

**Comment by MorganEdgerton** [comment]
No I haven't tried yet. I can fix it when i am focusing on this on monday
