### ISSUE TITLE
create presentation

### ISSUE THREAD

**Issue by spencer-shadley** [spencer-shadley/austinparks#4]

**Comment by pchiquini** [comment]
I got this started.
(sent the link to the groupMe)

**Comment by spencer-shadley** [comment]
Right. I have the link as https://docs.google.com/presentation/d/1I_NwoP1294liIHpUUF-CIvK7LycMDW_7FCq-hMsfJ8U/edit

This issue was in reference to actually filling out the details of the presentation, the skeleton you made is a great first step though.

**Comment by pchiquini** [comment]
gotcha gotcha. 
I'm thinking we can make it super brief due to the amount of time that we have. 
(2.5 minutes per team haha)

PER TEAM
one slide:
stating the things our community partner wanted. 
the goals of the project
second slide:
demonstration of the web application

**Comment by spencer-shadley** [comment]
Definitely, I think most of the time will be spent in our demos, rather than in the slides. We don't need to worry about the presentation too much.

**Comment by aliseisaksen** [comment]
The client's requirements, the goals, --and even our demo-- will be largely the same information between our groups. I would instead focus on team4's unique challenge of working with poor trail data and team 5's responsive challenges.

**Comment by aliseisaksen** [comment]
And then we can collectively explain the client's needs and our project goal as a supergroup and then show the demo in one go at the end.

**Comment by spencer-shadley** [comment]
Sounds good, we can toss in some other buzz words too like how it's set to scale and whatnot.

**Comment by pchiquini** [comment]
so I'm adding stuff to the presentation right now
but yeah I agree:
The goals and expectations are the same so put those in a slide

**Comment by pchiquini** [comment]
so we only need like 5 slides on our presentation
1 - welcome page
2 - goals of the project(s)
3 - trails challenges
4 - pool challenges
5 - web demo (lets go to austin and check it out)

**Comment by aliseisaksen** [comment]
Yup! That's perfect!
